### ISSUE TITLE
Use without `require`?

### ISSUE THREAD

**Issue by TrevorBurnham** [paulnicholson/coffee-filter#1]
I'm glad to see this gem—the various coffee-haml-filter forks were pretty undermaintained—but I'm curious: Is there any way to get around the requirement that I use a `require 'coffee-filter'` from Ruby code before using the filter? If I simply do

```
gem install coffee-filter
haml example.haml
```

(where `example.haml` contains your example code), I get

```
Haml error on line 3: Filter "coffeescript" is not defined.
  Use --trace for backtrace.
```

**Comment by paulnicholson** [comment]
I had not thought of it's usage with the haml command line.
Try:
`haml -rubygems -r 'coffee-filter' example.haml`

**Comment by TrevorBurnham** [comment]
Works like a charm, thanks. (Also works without the `-rubygems` flag, at least on my system.)

There's no way to put `coffee-filter` somewhere on my system where Haml will find it by default?

**Comment by paulnicholson** [comment]
`alias haml="haml -rubygems -r 'coffee-filter'"`
I don't know of any other way atm.

**Comment by TrevorBurnham** [comment]
Ha, thanks. :)
