### ISSUE TITLE
undefined method `lazy_require' for Coffee::Filter::Coffeescript:Module 

### ISSUE THREAD

**Issue by TylerRick** [paulnicholson/coffee-filter#10]
I got this error when I upgraded to haml 4.0 release candidate:

```
gems/coffee-filter-0.1.2/lib/coffee-filter/coffeescript.rb:8:in `<module:Coffeescript>': undefined method `lazy_require' for Coffee::Filter::Coffeescript:Module (NoMethodError)
```

Looks like haml 4.0 is going to be officially released in 2 days: https://github.com/indirect/haml-rails/pull/38

Fortunately, it looks like it includes official support for `:coffee` / `:coffeescript` filters so this gem will no longer be needed. (Thanks for providing it in the meantime though!)

**Comment by norman** [comment]
I just sent a pull request to update the deps in #11. As @TylerRick says, thanks for maintaining this throughout the 3.1 release! 3.1 will still be maintained for bug fixes for quite a while, so I'm sure there will still be plenty of people who want to use this gem.

**Comment by paulnicholson** [comment]
Yes, thanks for the pull request. I've merged it and pushed a new version to rubygems.
