### ISSUE TITLE
"coffee-filter" gem giving undefine method error.

### ISSUE THREAD

**Issue by vikask** [paulnicholson/coffee-filter#12]
when i'm adding new gem "cocaine" or "coffee-script" with "coffee-filter" gem.then i'm getting this error--

![asdf](https://f.cloud.github.com/assets/1697663/191760/1ad8e788-7f48-11e2-82f5-e7377b6b583e.png)

**Comment by paulnicholson** [comment]
What version of haml are you using?

**Comment by vikask** [comment]
i'm using haml (4.0) and coffee-filter (0.1.1).then getting this error.

**Comment by paulnicholson** [comment]
@vikask Remove the coffee-filter gem….coffee-filter is built into haml now.

**Comment by vikask** [comment]
ok.thanks...
