### ISSUE TITLE
Interpolated strings contained in :coffeescript filter get interpreted by Ruby instead of Barista

### ISSUE THREAD

**Issue by brenttheisen** [paulnicholson/coffee-filter#3]
The code below will display a alert with whatever version of Ruby you are using. Haven't gone under the hood yet but I couldn't think of any obvious way to get Barista to parse these interpolated strings instead of Haml/Ruby.

``` haml
- content_for :javascripts do
  :coffeescript
    alert "This is coming from Rubyland: #{RUBY_VERSION}"
```

**Comment by paulnicholson** [comment]
Yes, I am aware of that and it has not been much of an issue for me.
It would be easy to disable the ruby interpolation and pass it through but sometime its useful to have ruby parse it.
In my case I just worked around it but I am willing to take a look at any patches.

**Comment by brenttheisen** [comment]
I can see why it would be useful to allow Ruby to parse interpolated strings. Personally, I prefer to embed data that comes from Ruby in the DOM using custom data attributes instead of embedding it in JS. To each his own though. It's not too painful to use concatenation instead of interpolation so I'll close this out. Thanks for making this gem available.

**Comment by TylerRick** [comment]
I ran into this as well. Since this is a HAML file that's being parsed, it appears that the solution is as easy as escaping the `#` so that HAML treats it as a literal. That seems to allow it to pass it on to the coffeescript filter as `#{}` as intended. Try this:

``` coffeescript
  RUBY_VERSION = '1.9.9'
  alert "This is coming from CoffeScript: \#{RUBY_VERSION}"
```
