### ISSUE TITLE
Usage in helpers & ruby code?

### ISSUE THREAD

**Issue by zinkkrysty** [paulnicholson/coffee-filter#5]
Is there a way that it can be used in helpers? 

like this:

``` ruby
coffee_filter_tag("alert 'tag created' if 1=1")
```

**Comment by paulnicholson** [comment]
I would prefer `coffeescript_tag` as the helper name and that it behaves like the [javascript_tag](http://api.rubyonrails.org/classes/ActionView/Helpers/JavaScriptHelper.html#method-i-javascript_tag) helper.
I don't have the time to make those changes but will merge a pull request that contains tests to go along with the change and doesn't force a dependency on Rails. I would imagine a module like CoffeeFilter::ViewHelpers that contains the helper and gets auto included in ActionView if defined.

**Comment by paulnicholson** [comment]
Closing this issue since this library is mostly unnecessary now.
