### ISSUE TITLE
Filter "coffeescript" is not defined.

### ISSUE THREAD

**Issue by jesha** [paulnicholson/coffee-filter#6]
Hello

I have a following problem. I'm using HAML views in my rails app and i wanted to use some coffeescript in them. I added Barista to my gemfile:

gem 'haml'
gem 'coffee-filter'

and ran bundle install.
But when I try to use :coffeescript filter I get:

Haml::Error in carts#index

Showing /home/jesha/ror/prefab/app/views/carts/index.html.haml where line #7 raised:

Filter "coffeescript" is not defined.
Extracted source (around line #7):

4:
5: %br
6: 
7: :coffeescript
8: &nbsp;&nbsp;alert("test")
9: 
10: %table

Do you know what am I doing wrong?

**Comment by mhaseebkhan** [comment]
Facing the same problem with Heroku. Any luck so far?

**Comment by silvenon** [comment]
`require 'coffee-filter'`

**Comment by paulnicholson** [comment]
Any news on this?

**Comment by silvenon** [comment]
I don't know about others, but I got the same problem, then I required `coffee-filter` and it worked. I don't think there are any problems with the gem, just a hint in the README would be nice.

**Comment by thawatchai** [comment]
I had the same problem in production and fixed by putting `require 'coffee-filter'` in application.rb. There is no problem in development, though.

Please put it in the README.

**Comment by memelet** [comment]
I get this same error even in development.

**Comment by paulnicholson** [comment]
I'm not sure what is causing this problem for you. I just generated a simple rails project to test this with the latest rails and I do not need anything more than the line in the Gemfile. You can check it out at https://github.com/paulnicholson/coffee-filter-test.

**Comment by paulnicholson** [comment]
The only changes I made beyond `rails new coffee-filter-test` are the following files.
https://github.com/paulnicholson/coffee-filter-test/blob/master/Gemfile#L4-5
https://github.com/paulnicholson/coffee-filter-test/blob/master/config/routes.rb#L2
https://github.com/paulnicholson/coffee-filter-test/blob/master/app/controllers/application_controller.rb#L4-6
https://github.com/paulnicholson/coffee-filter-test/blob/master/app/views/layouts/application.html.haml
https://github.com/paulnicholson/coffee-filter-test/blob/master/app/views/application/index.html.haml

**Comment by memelet** [comment]
Yes, my problem was a decoy. I did not restart the server after adding the gem. All is working great now. Sorry for the noise.

**Comment by paulnicholson** [comment]
ok, no problem! To the rest of you, let me know if you're still having issues and if the test project works for you.
