### ISSUE TITLE
ExecJS::RuntimeError

### ISSUE THREAD

**Issue by k2xl** [paulnicholson/coffee-filter#8]
Some strange errors I'm getting today when I rebooted my rails app
Anytime I use :coffeescript I get an error.

For example

  :coffeescript
    alert("a")

The page results in:

---

ExecJS::RuntimeError in Users#index

Showing <path>/index.html.haml where line # raised:

["ok","(function() {\n\n  alert(\"a\");\n\n}).call(this);\n"]

---

Which is weird because it looks like the script actually converted into coffeescript, but now it's just erroring anytime. I'm using thin web server on windows, and I have execjs installed. i'm not 100% sure it's the coffee-filter, but I do know that all my other coffeescripts in external files are being loaded OK.

**Comment by k2xl** [comment]
more specific error:
ActionView::Template::Error (["ok","(function() {\n\n  alert(\"a\");\n\n}).call(this);\n"]):
  execjs (1.4.0) lib/execjs/external_runtime.rb:142:in `exec_runtime'
  execjs (1.4.0) lib/execjs/external_runtime.rb:28:in`block in exec'
  execjs (1.4.0) lib/execjs/external_runtime.rb:41:in `compile_to_tempfile'
  execjs (1.4.0) lib/execjs/external_runtime.rb:27:in`exec'
  execjs (1.4.0) lib/execjs/external_runtime.rb:19:in `eval'
  execjs (1.4.0) lib/execjs/external_runtime.rb:33:in`call'

**Comment by paulnicholson** [comment]
Using what rails & haml versions? Does the [coffee-filter-test](https://github.com/paulnicholson/coffee-filter-test) project work for you?
I've heard that haml 3.2 will have :coffeescript built in. https://github.com/haml/haml/issues/466

**Comment by paulnicholson** [comment]
Closing this issue since I haven't heard anything back.
